//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADON
    {
        public string MAHD { get; set; }
        public string MAHOA { get; set; }
        public Nullable<int> SOLUONGBAN { get; set; }
        public Nullable<double> GIABAN { get; set; }
    
        public virtual HOADON HOADON { get; set; }
    }
}
