//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOVANG
    {
        public string MAGIOVANG { get; set; }
        public Nullable<System.TimeSpan> GIOBATDAUUD { get; set; }
        public Nullable<System.TimeSpan> GIOKETTHUCUD { get; set; }
        public Nullable<int> NGAYTRONGTUAN { get; set; }
    }
}
