//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA
    {
        public string MAHOA { get; set; }
        public string TENHOA { get; set; }
        public string MALOAIHOA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DONVI { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual LOAIHOA LOAIHOA { get; set; }
    }
}
