//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public string MANCC { get; set; }
        public string TENNCC { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public Nullable<int> GIANHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
    }
}
