//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public string MAPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string MaNV { get; set; }
        public string MANCC { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
